# -*- coding: utf-8 -*-
"""T6_24_02_23_chieu_FUZZY.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1YHYx_TZs7cNcVT_AAOlRVQFGFAdGhCog
"""

import numpy as np
import skfuzzy as fuzz
import matpotlib.pyplot as plt

pip install Fuzzy

import numpy as np
import skfuzzy as fuzz
import matpotlib.pyplot as plt

# Commented out IPython magic to ensure Python compatibility.
# %pip install scipy
# %pip install -U scikit-fuzzy

import numpy as np
import skfuzzy as fuzz
import matpotlib.pyplot as plt
x=np.average(30,8111)
slow=fuzz.trimf(x,[30,40,50])
plt.figure()
plt.plot(x,slow,'r',linewidth=1.5,label='slow')

import numpy as np
import skfuzzy as fuzz
import matplotlib.pyplot as plt
x = np.arange(30,81,1)
slow = fuzz.trimf(x,[30,40,50])
medium = fuzz.trimf(x,[40,50,60])
plt.figure()
plt.plot(x,slow,'r',linewidth=1.5,label='slow')
plt.plot(x,medium,'r',linewidth=1.5,label='slow')

import numpy as np
import skfuzzy as fuzz
import matplotlib.pyplot as plt
x = np.arange(30,81,1)
slow = fuzz.trapmf(x,[30,40,40,50])
medium = fuzz.trapmf(x,[40,50,50,60])
plt.figure()
plt.plot(x,slow,'r',linewidth=1.5,label='slow')
plt.plot(x,medium,'b',linewidth=1.5,label='slow')

import numpy as np
import skfuzzy as fuzz
import matplotlib.pyplot as plt
x = np.arange(30,81,1)
slow = fuzz.gaussmf(x,30,5)
medium = fuzz.gaussmf(x,40,6)
plt.figure()
plt.plot(x,slow,'r',linewidth=1.5,label='slow')
plt.plot(x,medium,'b',linewidth=1.5,label='slow')

import numpy as np
import skfuzzy as fuzz
from skfuzzy import control as ctrl

food = ctrl.Antecedent(np.arange(0,11,1),'food')
service = ctrl.Antecedent(np.arange(0,11,1),'service')
tip = ctrl.Consequent(np.arange(10,31,1),'tip')

food['poor'] = fuzz.trimf(food.universe,[0,0,5])
food['average'] = fuzz.trimf(food.universe,[0,5,10])
food['good'] = fuzz.trimf(food.universe,[5,10,10])

service['poor'] = fuzz.trimf(service.universe,[0,0,5])
service['average'] = fuzz.trimf(service.universe,[0,5,10])
service['good'] = fuzz.trimf(service.universe,[5,10,10])

tip['less'] = fuzz.trimf(tip.universe,[10,10,20])
tip['average'] = fuzz.trimf(tip.universe,[10,20,30])
tip['much'] = fuzz.trimf(tip.universe,[20,30,30])

food.view()
service.view()
tip.view()

service['average'].view() #nhấn mạnh average

from skfuzzy.control.controlsystem import ControlSystemSimulation
rule1 = ctrl.Rule(food['poor']&service['poor'],tip['less'])
rule2 = ctrl.Rule(food['poor']&service['average'],tip['less'])
rule3 = ctrl.Rule(food['poor']&service['good'],tip['average'])
rule4 = ctrl.Rule(food['average']&service['poor'],tip['less'])
rule5 = ctrl.Rule(food['average']&service['average'],tip['average'])
rule6 = ctrl.Rule(food['average']&service['good'],tip['much'])
rule7 = ctrl.Rule(food['good']&service['poor'],tip['less'])
rule8 = ctrl.Rule(food['good']&service['average'],tip['much'])
rule9 = ctrl.Rule(food['good']&service['good'],tip['much'])
tipping_ctrl = ctrl.ControlSystem([rule1,rule2,rule3,rule4,rule5,rule6,rule7,rule8,rule9])
tipping = ControlSystemSimulation(tipping_ctrl)
tipping.input['food']=10
tipping.input['service']=10
tipping.compute()
print(tipping.output['tip'])
tip.view(sim=tipping)

import numpy as np
import skfuzzy as fuzz
import matplotlib.pyplot as plt

time = ctrl.Antecedent(np.arange(10,181,1),'time')
rice = ctrl.Antecedent(np.arange(0.2,1.5,1),'rice')
power = ctrl.Consequent(np.arange(0,100,1),'power')

time['very fast'] = fuzz.trimf(time.universe,[10,10,20])
time['fast'] = fuzz.trimf(time.universe,[20,30,40])
time['average'] = fuzz.trimf(time.universe,[20,40,50])
time['slow'] = fuzz.trimf(time.universe,[60,80,100])
time['very slow'] = fuzz.trimf(time.universe,[120,180,180])


rice['less'] = fuzz.trimf(rice.universe,[0.2,0.2,1])
rice['average'] = fuzz.trimf(rice.universe,[0.2,1,1.5])
rice['much'] = fuzz.trimf(rice.universe,[1,1.5,1.5])

power['very weak'] = fuzz.trimf(power.universe,[0,0,10])
power['weak'] = fuzz.trimf(power.universe,[10,20,30])
power['average'] = fuzz.trimf(power.universe,[20,40,50])
power['strong'] = fuzz.trimf(power.universe,[60,70,80])
power['very strong'] = fuzz.trimf(power.universe,[80,100,100])

time.view()
rice.view()
power.view()